### ISSUE TITLE
你好，运行的时候报这个错。可能是什么问题呢

### ISSUE THREAD

**Issue by EdisonChenZX** [formateddd/pornhub#20]
File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'C:\\Users\\taw\\Desktop\\d\\Pornhub\\logs\\C:'

**Comment by formateddd** [comment]
mkdir是运行在Linux上的命令， windows不行滴。而且要能连上ph网站，你再研究一下

**Comment by EdisonChenZX** [comment]
那再windows上请问要怎么运行

**Comment by formateddd** [comment]
mkdir改成md， 但是你如果不会翻墙的话 还是下载不了

**Comment by EdisonChenZX** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\taw\Desktop\d\Pornhub\crawler.py", line 14, in <module>
    logger.add("logs/%s.log" % __file__.rstrip('.py'), format="{time:MM-DD HH:mm:ss} {level} {message}")
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\site-packages\loguru\_logger.py", line 599, in add
    sink = FileSink(path, **kwargs)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\site-packages\loguru\_file_sink.py", line 57, in __init__
    self.initialize_file(rename_existing=False)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\site-packages\loguru\_file_sink.py", line 83, in initialize_file
    os.makedirs(new_dir, exist_ok=True)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 210, in makedirs
Traceback (most recent call last):
    makedirs(head, mode, exist_ok)
  File "<string>", line 1, in <module>
  [Previous line repeated 1 more times]
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 220, in makedirs
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'C:\\Users\\taw\\Desktop\\d\\Pornhub\\logs\\C:'
    exitcode = _main(fd)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\taw\Desktop\d\Pornhub\crawler.py", line 14, in <module>
    logger.add("logs/%s.log" % __file__.rstrip('.py'), format="{time:MM-DD HH:mm:ss} {level} {message}")
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\site-packages\loguru\_logger.py", line 599, in add
    sink = FileSink(path, **kwargs)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\site-packages\loguru\_file_sink.py", line 57, in __init__
    self.initialize_file(rename_existing=False)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\site-packages\loguru\_file_sink.py", line 83, in initialize_file
    os.makedirs(new_dir, exist_ok=True)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 1 more times]
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'C:\\Users\\taw\\Desktop\\d\\Pornhub\\logs\\C:'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\taw\Desktop\d\Pornhub\crawler.py", line 14, in <module>
    logger.add("logs/%s.log" % __file__.rstrip('.py'), format="{time:MM-DD HH:mm:ss} {level} {message}")
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\site-packages\loguru\_logger.py", line 599, in add
    sink = FileSink(path, **kwargs)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\site-packages\loguru\_file_sink.py", line 57, in __init__
    self.initialize_file(rename_existing=False)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\site-packages\loguru\_file_sink.py", line 83, in initialize_file
Traceback (most recent call last):
    os.makedirs(new_dir, exist_ok=True)
  File "<string>", line 1, in <module>
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 210, in makedirs
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    makedirs(head, mode, exist_ok)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 210, in makedirs
    exitcode = _main(fd)
    makedirs(head, mode, exist_ok)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 210, in makedirs
    prepare(preparation_data)
    makedirs(head, mode, exist_ok)
  [Previous line repeated 1 more times]
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 220, in makedirs
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'C:\\Users\\taw\\Desktop\\d\\Pornhub\\logs\\C:'
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\taw\Desktop\d\Pornhub\crawler.py", line 14, in <module>
    logger.add("logs/%s.log" % __file__.rstrip('.py'), format="{time:MM-DD HH:mm:ss} {level} {message}")
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\site-packages\loguru\_logger.py", line 599, in add
    sink = FileSink(path, **kwargs)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\site-packages\loguru\_file_sink.py", line 57, in __init__
    self.initialize_file(rename_existing=False)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\site-packages\loguru\_file_sink.py", line 83, in initialize_file
    os.makedirs(new_dir, exist_ok=True)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 1 more times]
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'C:\\Users\\taw\\Desktop\\d\\Pornhub\\logs\\C:'





------------------ 原始邮件 ------------------


发件人: "The handsome boy"<notifications@github.com>;

发送时间: 2019年1月25日(星期五) 下午2:58

收件人: "formateddd/pornhub"<pornhub@noreply.github.com>;

抄送: "大雄"<1648458952@qq.com>; "Author"<author@noreply.github.com>; 

主题: Re: [formateddd/pornhub] 你好，运行的时候报这个错。可能是什么问题呢 (#20)




mkdir改成md， 但是你如果不会翻墙的话 还是下载不了

**Comment by EdisonChenZX** [comment]
这个是我完整的错误

**Comment by EdisonChenZX** [comment]
本来想发邮件的，但是失败了

**Comment by EdisonChenZX** [comment]
我的vpn一直都是打开的。

**Comment by formateddd** [comment]
注意看报错，mkdir改成md，在crawler.py里76行

**Comment by EdisonChenZX** [comment]
File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
  File "C:\Users\taw\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    exec(code, run_globals)
    prepare(preparation_data)
  File "C:\Users\taw\Desktop\d\Pornhub\crawler.py", line 14, in <modul

这个第十四行logger.add("logs/%s.log" % __file__.rstrip('.py'), format="{time:MM-DD HH:mm:ss} {level} {message}")
这个，再windows也应该改吗？不好意思，大哥，我python不是很熟

**Comment by formateddd** [comment]
这个库我没有在windows下用过，你可以把logger都改成print，日志无所谓

**Comment by EdisonChenZX** [comment]
File "c:/Users/taw/Desktop/d/Pornhub/crawler.py", line 77, in run
    os.md(path)
AttributeError: module 'os' has no attribute 'md'

**Comment by EdisonChenZX** [comment]
这个是没有md这个命令码

**Comment by formateddd** [comment]
用os.system()直接执行命令，你看下这个库的用法

**Comment by EdisonChenZX** [comment]
非常感谢。成功了

**Comment by EdisonChenZX** [comment]
请问，如果要在手机运行，要怎么弄

**Comment by formateddd** [comment]
不会做app，你会的话帮忙做一下啊

**Comment by EdisonChenZX** [comment]
我是搞javaweb的。emmmmm。话说，请问那个download.txt可不可以放多哥视频的字符串。还是每次只能放一个。

**Comment by formateddd** [comment]
可以放呀， 每行一个后缀就好了
