### ISSUE TITLE
It has been reported wrong.

### ISSUE THREAD

**Issue by tyzcly** [formateddd/pornhub#21]
in cmd:
D:\Cwork\porn\pornhub-master>python crawler.py webm
Traceback (most recent call last):
  File "crawler.py", line 12, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'
---------------------------------------------------------------------------------------------------------------
in pycarm
D:\Btool\Python37\python.exe D:/Cwork/porn/pornhub-master/crawler.py
Traceback (most recent call last):
  File "D:/Cwork/porn/pornhub-master/crawler.py", line 14, in <module>
    logger.add("logs/%s.log" % __file__.rstrip('.py'), format="{time:MM-DD HH:mm:ss} {level} {message}")
  File "D:\Btool\Python37\lib\site-packages\loguru\_logger.py", line 599, in add
    sink = FileSink(path, **kwargs)
  File "D:\Btool\Python37\lib\site-packages\loguru\_file_sink.py", line 57, in __init__
    self.initialize_file(rename_existing=False)
  File "D:\Btool\Python37\lib\site-packages\loguru\_file_sink.py", line 83, in initialize_file
    os.makedirs(new_dir, exist_ok=True)
  File "D:\Btool\Python37\lib\os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "D:\Btool\Python37\lib\os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "D:\Btool\Python37\lib\os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "D:\Btool\Python37\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'D:\\Cwork\\porn\\pornhub-master\\logs\\D:'

**Comment by formateddd** [comment]
#20
